version: '3'
services: 
  db:
    image: postgres
    restart: always
    environment: 
      - POSTGRES_DB=atelie
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    volumes: 
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    tty: true
    build: .
    volumes: 
      - .:/atelie/back
      - /home/app/library/node_modules
    ports: 
      - "3333:3333"